app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000

organization:
  name: My Company

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'

techdocs:
  builder: local
  generator:
    runIn: docker
  publisher:
    type: local

auth:
  environment: development
  providers:
    guest: {}

scaffolder: {}

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, Template]
  locations:
    - type: file
      target: ../../examples/entities.yaml

    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ../../examples/template/azure/storage-account/storage-account-standard-template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ../../examples/template/azure/storage-account/storage-account-ai-template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ../../examples/template/azure/aks-cluster/aks-cluster-standard-template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ../../examples/template/azure/aks-cluster/aks-cluster-ai-template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]

kubernetes: {}

permission:
  enabled: false
